#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap           9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## border colors
bspc config active_border_color  '#313846'
bspc config normal_border_color  '#09040A'
bspc config focused_border_color '#313846'

bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
