#!/usr/bin/env bash

source $HOME/.config/scripts/setup-scripts/logs.sh
log_file_bspwm="$HOME/.local/share/logs/bspwm.log"

function global_configs() {
  
  bspc config border_width         3
  bspc config window_gap           8

  bspc config split_ratio          0.52
  bspc config borderless_monocle   true
  bspc config gapless_monocle      true

  bspc rule -a firefox desktop='^3'
  bspc rule -a brave desktop='^3'
  bspc rule -a discord desktop='^4'
  bspc rule -a Screenkey manage=off
  
  log_info "Setup global configs" "$log_file_bspwm"
}
