#!/usr/bin/env bash

source $HOME/.config/scripts/setup-scripts/logs.sh
log_file_bspwm="$HOME/.local/share/logs/bspwm.log"

function configuration_workspaces(){

  local monitors=$(xrandr --query | grep -E '^[A-Za-z0-9\-]+.*[0-9]+x[0-9]+' | cut -d' ' -f1)
  for monitor in $monitors; do 
    log_info "Encontrado monitor: ${monitor}" "$log_file_bspwm"
    bspc monitor "${monitor}" -d '1' '2' '3' '4' '5'
  done
  
  ## Delete extra workspace
  bspc config merge_overlapping_monitors true
  bspc desktop Desktop --remove &
}
##OLD ONE
#external_monitor=$(xrandr --query | grep 'HDMI-1')
#if [[ $external_monitor = *connected* ]]; then
#    xrandr --output HDMI-1 --mode 1920x1080 --primary --rotate normal
#    xrandr --output eDP-1 --off
#fi
